cp -v source/texk/web2c/luatexdir/lua/luatex-core.c 	 /home/luigisvn/projects/luatex/branches/experimental/source/texk/web2c/luatexdir/lua/luatex-core.c
cp -v source/texk/web2c/luatexdir/lua/luatex-core.lua 	 /home/luigisvn/projects/luatex/branches/experimental/source/texk/web2c/luatexdir/lua/luatex-core.lua
cp -v source/texk/web2c/luatexdir/luatex.c 	 /home/luigisvn/projects/luatex/branches/experimental/source/texk/web2c/luatexdir/luatex.c
cp -v source/texk/web2c/luatexdir/luatex_svnversion.h 	 /home/luigisvn/projects/luatex/branches/experimental/source/texk/web2c/luatexdir/luatex_svnversion.h
cp -v source/texk/web2c/luatexdir/pdf/pdfgen.w 	 /home/luigisvn/projects/luatex/branches/experimental/source/texk/web2c/luatexdir/pdf/pdfgen.w
