cp -v luatexdir/lua/lnewtokenlib.c 	 /home/luigisvn/projects/texlive/trunk/Build/source/texk/web2c/luatexdir/lua/lnewtokenlib.c
cp -v luatexdir/lua/lpdfelib.c 	 /home/luigisvn/projects/texlive/trunk/Build/source/texk/web2c/luatexdir/lua/lpdfelib.c
cp -v luatexdir/luatex_svnversion.h 	 /home/luigisvn/projects/texlive/trunk/Build/source/texk/web2c/luatexdir/luatex_svnversion.h
cp -v mplibdir/mp.w 	 /home/luigisvn/projects/texlive/trunk/Build/source/texk/web2c/mplibdir/mp.w
